### ISSUE TITLE
Type Error

### ISSUE THREAD

**Issue by pritamkandula** [Scrape-Goat/scrapegoat#1]
**Describe the bug**
While running generateData() a type error was encountered, which displays

 **`Search() got an unexpected keyword argument 'tld'`** 

**To Reproduce**
``` python
  # scrape and download data
    topic = " cricket"
    language = 'hi'
    generateData(topic, language, n_links=20

```

**Comment by Navaneeth-Sharma** [comment]
this issue is created by installing a package called  `googlesearch-python`. So the main code need to updated. 

reference: https://stackoverflow.com/questions/70686557/python-googlesearch-module-error-typeerror-search-got-an-unexpected-keywor
